language: node_js
node_js:
  - '14'
install:
  - yarn install --frozen-lockfile
script:
  - yarn run build
  - yarn run lint
  - yarn run test
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: Is75c3CJdeBlyZt1GrX6LazeNz5tk25LRAP99AB9OZEZXXmJNW+k1ckEHY5O8mbXjqE7fkYn6JiNQNf3/1+0GKu/k2sBs3dXHdbx1jqWCSpmfs6T19N681GvMD1PJ3iyHr/XogNCFh1cXr0XHEQhBIE/33eGI4V5Hm5ox9elEDAEYSMVTpKIrDnkeqOjKEWcjwiz/RP1qRHiWebHKoIMpm3XguPGSOWegkiYyX1vh4OB3/pRnNEjxyPajSlEDZYiKP/KSWNQ2PkBQgLSDHscVK7it1YuTjyeudk8RtK2n3MHRRHV6+ZetfRgzhotvhO9MCBiPvFzTE+E92g6lFfoxKsDQDPoE8O3PjQBCnKvofMF8dGYNoPH3mfu+5bdMqOCPewrpEhU2kO6t2g0j4IPpha9aCSqFWg7zx3xsSJ/JuRNqe0y9N08pbEWwgVMRoRKQTC2QY8FF+mM1CBs1arJ5oVFVePwKRGEoug8TeX8TisZEeaL2PR7MFSzY1OR98RGQsQAeXWrxR3Ib+z87r05PByXevtgNHjwRQlzPi0UsZiIBbY0KTbho2rHCBAMz3DXuECmPrcsPBt19T2h3MdjdS/yKWpwoO2xae+ws9WwxBNSODO7vAOVyRApLw23cfjopFLiAnZbShJil0fD2skt1/bi2Oe8rUd3urzhpSR67Js=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 14
