language: node_js
node_js:
  - '13'
install:
  - yarn install --frozen-lockfile
script:
  - yarn run build
  - yarn run lint
  - yarn run test
  - yarn run check
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: ''
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 13
